apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: github-repo-test-ci-  # Name of this Workflow
spec:
  entrypoint: main           # Defines "whalesay" as the "main" template
  arguments:
    parameters:
      - name: event
      - name: ref
      - name: revision
  templates:
  - name: main               # Defining the "whalesay" template
    inputs:
      parameters:
        - name: event
        - name: ref
        - name: revision
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.revision}}"]      # This template runs "cowsay" in the "whalesay" image with arguments "hello world"
