apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-ci-  # Name of this Workflow
spec:
  entrypoint: whalesay           # Defines "whalesay" as the "main" template
  arguments:
    parameters:
      - name: param
  templates:
  - name: whalesay               # Defining the "whalesay" template
    inputs:
      parameters:
        - name: param
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.param}}"]      # This template runs "cowsay" in the "whalesay" image with arguments "hello world"
